/**
 * Esmaül Hüsna — Allah'ın 99 Güzel İsmi
 */

const ESMA = [
    { ar: 'الرَّحْمَنُ', tr: 'Rahman', en: 'The Most Gracious', trMean: 'Çok merhamet eden', enMean: 'The Most Compassionate' },
    { ar: 'الرَّحِيمُ', tr: 'Rahim', en: 'The Most Merciful', trMean: 'Çok merhametli', enMean: 'The Most Merciful' },
    { ar: 'الْمَلِكُ', tr: 'Melik', en: 'The King', trMean: 'Mülkün gerçek sahibi', enMean: 'The Sovereign Lord' },
    { ar: 'الْقُدُّوسُ', tr: 'Kuddüs', en: 'The Most Holy', trMean: 'Her noksanlıktan uzak', enMean: 'The Most Sacred' },
    { ar: 'السَّلَامُ', tr: 'Selam', en: 'The Source of Peace', trMean: 'Selamet veren', enMean: 'The Bestower of Peace' },
    { ar: 'الْمُؤْمِنُ', tr: 'Mü\'min', en: 'The Guardian of Faith', trMean: 'Güven veren', enMean: 'The Inspirer of Faith' },
    { ar: 'الْمُهَيْمِنُ', tr: 'Müheymin', en: 'The Protector', trMean: 'Koruyup gözeten', enMean: 'The Guardian' },
    { ar: 'الْعَزِيزُ', tr: 'Aziz', en: 'The Almighty', trMean: 'Üstün ve güçlü', enMean: 'The Mighty' },
    { ar: 'الْجَبَّارُ', tr: 'Cebbar', en: 'The Compeller', trMean: 'Dilediğini yaptıran', enMean: 'The Irresistible' },
    { ar: 'الْمُتَكَبِّرُ', tr: 'Mütekebbir', en: 'The Greatest', trMean: 'Büyüklükte eşsiz', enMean: 'The Supreme' },
    { ar: 'الْخَالِقُ', tr: 'Halık', en: 'The Creator', trMean: 'Yaratan', enMean: 'The Creator' },
    { ar: 'الْبَارِئُ', tr: 'Bari', en: 'The Evolver', trMean: 'Kusursuz yaratan', enMean: 'The Maker' },
    { ar: 'الْمُصَوِّرُ', tr: 'Musavvir', en: 'The Fashioner', trMean: 'Şekil veren', enMean: 'The Shaper' },
    { ar: 'الْغَفَّارُ', tr: 'Gaffar', en: 'The Forgiver', trMean: 'Çok bağışlayan', enMean: 'The Great Forgiver' },
    { ar: 'الْقَهَّارُ', tr: 'Kahhar', en: 'The Subduer', trMean: 'Her şeye galip', enMean: 'The All-Prevailing' },
    { ar: 'الْوَهَّابُ', tr: 'Vehhab', en: 'The Bestower', trMean: 'Karşılıksız veren', enMean: 'The Supreme Bestower' },
    { ar: 'الرَّزَّاقُ', tr: 'Rezzak', en: 'The Provider', trMean: 'Rızık veren', enMean: 'The All-Provider' },
    { ar: 'الْفَتَّاحُ', tr: 'Fettah', en: 'The Opener', trMean: 'Her türlü sıkıntıyı açan', enMean: 'The Supreme Solver' },
    { ar: 'اَلْعَلِيمُ', tr: 'Alim', en: 'The All-Knowing', trMean: 'Her şeyi bilen', enMean: 'The All-Knowing' },
    { ar: 'الْقَابِضُ', tr: 'Kabız', en: 'The Constrictor', trMean: 'Rızkı daraltan', enMean: 'The Restrainer' },
    { ar: 'الْبَاسِطُ', tr: 'Basıt', en: 'The Expander', trMean: 'Rızkı genişleten', enMean: 'The Reliever' },
    { ar: 'الْخَافِضُ', tr: 'Hafıd', en: 'The Abaser', trMean: 'Alçaltan', enMean: 'The Humiliator' },
    { ar: 'الرَّافِعُ', tr: 'Rafi', en: 'The Exalter', trMean: 'Yücelten', enMean: 'The Exalter' },
    { ar: 'الْمُعِزُّ', tr: 'Muiz', en: 'The Honorer', trMean: 'Yücelten, izzet veren', enMean: 'The Bestower of Honor' },
    { ar: 'المُذِلُّ', tr: 'Müzil', en: 'The Dishonorer', trMean: 'Zillete düşüren', enMean: 'The Abaser' },
    { ar: 'السَّمِيعُ', tr: 'Semi', en: 'The All-Hearing', trMean: 'Her şeyi işiten', enMean: 'The All-Hearing' },
    { ar: 'الْبَصِيرُ', tr: 'Basir', en: 'The All-Seeing', trMean: 'Her şeyi gören', enMean: 'The All-Seeing' },
    { ar: 'الْحَكَمُ', tr: 'Hakem', en: 'The Judge', trMean: 'Hükmeden', enMean: 'The Impartial Judge' },
    { ar: 'الْعَدْلُ', tr: 'Adl', en: 'The Just', trMean: 'Mutlak adil', enMean: 'The Utterly Just' },
    { ar: 'اللَّطِيفُ', tr: 'Latif', en: 'The Subtle One', trMean: 'Lütuf sahibi', enMean: 'The Gentle' },
    { ar: 'الْخَبِيرُ', tr: 'Habir', en: 'The All-Aware', trMean: 'Her şeyden haberdar', enMean: 'The All-Aware' },
    { ar: 'الْحَلِيمُ', tr: 'Halim', en: 'The Forbearing', trMean: 'Yumuşak davranan', enMean: 'The Clement' },
    { ar: 'الْعَظِيمُ', tr: 'Azim', en: 'The Magnificent', trMean: 'Büyüklükte son', enMean: 'The Magnificent' },
    { ar: 'الْغَفُورُ', tr: 'Gafur', en: 'The Forgiving', trMean: 'Çok bağışlayan', enMean: 'The All-Forgiving' },
    { ar: 'الشَّكُورُ', tr: 'Şekur', en: 'The Grateful', trMean: 'Az amele çok sevap veren', enMean: 'The Most Appreciative' },
    { ar: 'الْعَلِيُّ', tr: 'Aliyy', en: 'The Highest', trMean: 'Yüce', enMean: 'The Most High' },
    { ar: 'الْكَبِيرُ', tr: 'Kebir', en: 'The Greatest', trMean: 'Büyük', enMean: 'The Most Great' },
    { ar: 'الْحَفِيظُ', tr: 'Hafiz', en: 'The Preserver', trMean: 'Koruyucu', enMean: 'The All-Preserver' },
    { ar: 'المُقيِتُ', tr: 'Mukit', en: 'The Nourisher', trMean: 'Besleyen', enMean: 'The Sustainer' },
    { ar: 'الْحسِيبُ', tr: 'Hasib', en: 'The Reckoner', trMean: 'Hesap gören', enMean: 'The Reckoner' },
    { ar: 'الْجَلِيلُ', tr: 'Celil', en: 'The Majestic', trMean: 'Celal sahibi', enMean: 'The Majestic' },
    { ar: 'الْكَرِيمُ', tr: 'Kerim', en: 'The Generous', trMean: 'Cömert, kerem sahibi', enMean: 'The Most Generous' },
    { ar: 'الرَّقِيبُ', tr: 'Rakib', en: 'The Watchful', trMean: 'Gözleyici', enMean: 'The Vigilant' },
    { ar: 'الْمُجِيبُ', tr: 'Mucib', en: 'The Responsive', trMean: 'Dualara cevap veren', enMean: 'The Answerer' },
    { ar: 'الْوَاسِعُ', tr: 'Vasi', en: 'The All-Encompassing', trMean: 'Rahmeti geniş', enMean: 'The All-Encompassing' },
    { ar: 'الْحَكِيمُ', tr: 'Hakim', en: 'The Wise', trMean: 'Hikmet sahibi', enMean: 'The All-Wise' },
    { ar: 'الْوَدُودُ', tr: 'Vedud', en: 'The Loving', trMean: 'Çok seven', enMean: 'The Most Loving' },
    { ar: 'الْمَجِيدُ', tr: 'Mecid', en: 'The Glorious', trMean: 'Şanlı, şerefli', enMean: 'The Most Glorious' },
    { ar: 'الْبَاعِثُ', tr: 'Bais', en: 'The Resurrecter', trMean: 'Ölüleri dirilten', enMean: 'The Resurrector' },
    { ar: 'الشَّهِيدُ', tr: 'Şehid', en: 'The Witness', trMean: 'Her şeye şahit', enMean: 'The All-Witnessing' },
    { ar: 'الْحَقُّ', tr: 'Hakk', en: 'The Truth', trMean: 'Varlığı kesin olan', enMean: 'The Absolute Truth' },
    { ar: 'الْوَكِيلُ', tr: 'Vekil', en: 'The Trustee', trMean: 'Güvenilen vekil', enMean: 'The Ultimate Trustee' },
    { ar: 'الْقَوِيُّ', tr: 'Kaviyy', en: 'The Strong', trMean: 'Çok güçlü', enMean: 'The All-Strong' },
    { ar: 'الْمَتِينُ', tr: 'Metin', en: 'The Firm', trMean: 'Çok sağlam', enMean: 'The Steadfast' },
    { ar: 'الْوَلِيُّ', tr: 'Veliyy', en: 'The Protecting Friend', trMean: 'Dost', enMean: 'The Protecting Associate' },
    { ar: 'الْحَمِيدُ', tr: 'Hamid', en: 'The Praiseworthy', trMean: 'Övülmeye layık', enMean: 'The All-Praiseworthy' },
    { ar: 'الْمُحْصِي', tr: 'Muhsi', en: 'The Counter', trMean: 'Her şeyi sayan', enMean: 'The All-Enumerating' },
    { ar: 'الْمُبْدِئُ', tr: 'Mübdi', en: 'The Originator', trMean: 'Yoktan var eden', enMean: 'The Originator' },
    { ar: 'الْمُعِيدُ', tr: 'Muid', en: 'The Restorer', trMean: 'Tekrar yaratan', enMean: 'The Restorer' },
    { ar: 'الْمُحْيِي', tr: 'Muhyi', en: 'The Giver of Life', trMean: 'Can veren', enMean: 'The Giver of Life' },
    { ar: 'اَلْمُمِيتُ', tr: 'Mümit', en: 'The Taker of Life', trMean: 'Öldüren', enMean: 'The Creator of Death' },
    { ar: 'الْحَيُّ', tr: 'Hayy', en: 'The Ever-Living', trMean: 'Diri, hayat sahibi', enMean: 'The Ever-Living' },
    { ar: 'الْقَيُّومُ', tr: 'Kayyum', en: 'The Self-Existing', trMean: 'Her şeyi ayakta tutan', enMean: 'The Self-Subsisting' },
    { ar: 'الْوَاجِدُ', tr: 'Vacid', en: 'The Finder', trMean: 'İstediğini bulan', enMean: 'The Perceiver' },
    { ar: 'الْمَاجِدُ', tr: 'Macid', en: 'The Noble', trMean: 'Şerefli', enMean: 'The Illustrious' },
    { ar: 'الْوَاحِدُ', tr: 'Vahid', en: 'The One', trMean: 'Tek', enMean: 'The Unique' },
    { ar: 'اَلْأَحَدُ', tr: 'Ahad', en: 'The Only One', trMean: 'Bir olan', enMean: 'The Indivisible' },
    { ar: 'الصَّمَدُ', tr: 'Samed', en: 'The Eternal', trMean: 'Muhtaç olunmayan', enMean: 'The Eternal Refuge' },
    { ar: 'الْقَادِرُ', tr: 'Kadir', en: 'The Able', trMean: 'Gücü yeten', enMean: 'The All-Capable' },
    { ar: 'الْمُقْتَدِرُ', tr: 'Muktedir', en: 'The Powerful', trMean: 'Kudret sahibi', enMean: 'The All-Determiner' },
    { ar: 'الْمُقَدِّمُ', tr: 'Mukaddim', en: 'The Expediter', trMean: 'Öne alan', enMean: 'The Expediter' },
    { ar: 'الْمُؤَخِّرُ', tr: 'Muahhir', en: 'The Delayer', trMean: 'Arkaya bırakan', enMean: 'The Delayer' },
    { ar: 'الأوَّلُ', tr: 'Evvel', en: 'The First', trMean: 'İlk', enMean: 'The First' },
    { ar: 'الآخِرُ', tr: 'Ahir', en: 'The Last', trMean: 'Son', enMean: 'The Last' },
    { ar: 'الظَّاهِرُ', tr: 'Zahir', en: 'The Manifest', trMean: 'Aşikar olan', enMean: 'The Manifest' },
    { ar: 'الْبَاطِنُ', tr: 'Batın', en: 'The Hidden', trMean: 'Gizli olan', enMean: 'The Hidden' },
    { ar: 'الْوَالِي', tr: 'Vali', en: 'The Governor', trMean: 'İdare eden', enMean: 'The Patron' },
    { ar: 'الْمُتَعَالِي', tr: 'Müteali', en: 'The Most Exalted', trMean: 'Yüce', enMean: 'The Self-Exalted' },
    { ar: 'الْبَرُّ', tr: 'Berr', en: 'The Source of Goodness', trMean: 'İyilik eden', enMean: 'The Source of All Goodness' },
    { ar: 'التَّوَّابُ', tr: 'Tevvab', en: 'The Accepter of Repentance', trMean: 'Tövbeleri kabul eden', enMean: 'The Ever-Pardoning' },
    { ar: 'الْمُنْتَقِمُ', tr: 'Müntekim', en: 'The Avenger', trMean: 'İntikam alan', enMean: 'The Avenger' },
    { ar: 'العَفُوُّ', tr: 'Afüvv', en: 'The Pardoner', trMean: 'Çok affeden', enMean: 'The Supreme Pardoner' },
    { ar: 'الرَّؤُوفُ', tr: 'Rauf', en: 'The Compassionate', trMean: 'Şefkatli', enMean: 'The Most Kind' },
    { ar: 'مَالِكُ الْمُلْكِ', tr: 'Malikül Mülk', en: 'Owner of Sovereignty', trMean: 'Mülkün ebedi sahibi', enMean: 'Owner of All Sovereignty' },
    { ar: 'ذُوالْجَلَالِ وَالإكْرَامِ', tr: 'Zülcelali vel İkram', en: 'Lord of Majesty and Generosity', trMean: 'Celal ve ikram sahibi', enMean: 'Possessor of Majesty and Honor' },
    { ar: 'الْمُقْسِطُ', tr: 'Muksit', en: 'The Equitable', trMean: 'Adaletli', enMean: 'The Equitable' },
    { ar: 'الْجَامِعُ', tr: 'Cami', en: 'The Gatherer', trMean: 'Toplayan', enMean: 'The Assembler' },
    { ar: 'الْغَنِيُّ', tr: 'Ganiyy', en: 'The Rich', trMean: 'Zengin', enMean: 'The Self-Sufficient' },
    { ar: 'الْمُغْنِي', tr: 'Mugni', en: 'The Enricher', trMean: 'Zenginleştiren', enMean: 'The Enricher' },
    { ar: 'اَلْمَانِعُ', tr: 'Mani', en: 'The Preventer', trMean: 'Engelleyen', enMean: 'The Withholder' },
    { ar: 'الضَّارَّ', tr: 'Darr', en: 'The Distresser', trMean: 'Zarar veren', enMean: 'The Distresser' },
    { ar: 'النَّافِعُ', tr: 'Nafi', en: 'The Propitious', trMean: 'Fayda veren', enMean: 'The Propitious' },
    { ar: 'النُّورُ', tr: 'Nur', en: 'The Light', trMean: 'Nur, aydınlatıcı', enMean: 'The Light' },
    { ar: 'الْهَادِي', tr: 'Hadi', en: 'The Guide', trMean: 'Hidayet eden', enMean: 'The Guide' },
    { ar: 'الْبَدِيعُ', tr: 'Bedi', en: 'The Originator', trMean: 'Eşsiz yaratan', enMean: 'The Incomparable' },
    { ar: 'اَلْبَاقِي', tr: 'Baki', en: 'The Everlasting', trMean: 'Varlığı sonsuz', enMean: 'The Ever-Enduring' },
    { ar: 'الْوَارِثُ', tr: 'Varis', en: 'The Inheritor', trMean: 'Her şeyin varisi', enMean: 'The Supreme Inheritor' },
    { ar: 'الرَّشِيدُ', tr: 'Reşid', en: 'The Guide to Right Path', trMean: 'Doğru yola götüren', enMean: 'The Righteous Teacher' },
    { ar: 'الصَّبُورُ', tr: 'Sabur', en: 'The Patient', trMean: 'Çok sabırlı', enMean: 'The Forbearing' }
];

module.exports = { ESMA };
